---
- name: Provision Image
  hosts: default
  become: false
  gather_facts: false

  tasks:
  - name: Bootstrap Python 3
    raw: apk add python3

  - name: Set apk repositories
    template:
      src: apk-repositories.j2
      dest: /etc/apk/repositories

  - name: Install cloud-init, Netdata and Docker
    community.general.apk:
      name:
      - openssh-server-pam
      - cloud-init
      - netdata
      - docker
      update_cache: true

  - name: Configure SSH
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config

  - name: Configure cloud-init
    copy:
      src: cloud.cfg
      dest: /etc/cloud/cloud.cfg

  - name: Configure Netdata
    copy:
      src: netdata.conf
      dest: /etc/netdata/netdata.conf

  - name: Create Docker configuration directory
    file:
      state: directory
      path: /etc/docker

  - name: Configure Docker
    copy:
      src: docker.json
      dest: /etc/docker/daemon.json

  - name: Enable services
    service:
      name: "{{ item }}"
      enabled: true
    loop:
    - cloud-init
    - netdata
    - docker
